### ISSUE TITLE
Track API 1.1_1.12 Causes TPS reduction

### ISSUE THREAD

**Issue by ThePoshTux** [cam72cam/TrackAPI#3]
- Issue:
Installing track API 1.1 causes a far lower TPS compared to track API 1.0 despite being a freshly generated world with no apparent reason for TPS reduction. As shown in the logs attached below the TPS could drop to 5 when using Track API 1.1_1.12
This conclusion was reached by comparing the TPS of forge only, IR/Track API and finally track API only. After it was realised that the TPS impact was primarily caused by track API multiple java versions were tested and finally, a different track API (version 1.0_1.12) was tested. Version 1.0 of the Track API was found to have no performance impact.
- Game Info:
minecraft version 1.12.2
forge (from what I can tell so far any but 14.23.5.2768    14.23.5.2815    and 14.23.5.2795  were tested)
mods: only track API 1.1
memory: minimum allocated ram set to 4GB but max allocated was tested from a range of 4GB to 10GB
- System Info:
Windows 10 64 bit
I3-540 @4GHz
12GB RAM @ 1740MHz
1050Ti

Track API 1.1 logs:
[2019-02-15-7.log](https://github.com/cam72cam/TrackAPI/files/2869017/2019-02-15-7.log)
[debug-1.log](https://github.com/cam72cam/TrackAPI/files/2869026/debug-1.log)

Track API 1.0 log:
[latest.log](https://github.com/cam72cam/TrackAPI/files/2869022/latest.log)
[debug.log](https://github.com/cam72cam/TrackAPI/files/2869028/debug.log)

**Comment by cam72cam** [comment]
TrackAPI does absolutely nothing without ImmersiveRailroading or another mod which interacts with it.  You should double check your experimental setup and sample size for the tests you ran.

**Comment by Larky2k** [comment]
Iv tested and with latest forge and only Track API (latest) TPS drops to 8 with Max render distance on if i drop it to 12 then TPS goes back to 20. also tested with CodeChickenLib 1.8+(latest) on its own and that got 20TPS. Track API and IR(latest) together solid 20TPS even at Max Render.
