### ISSUE TITLE
track api 1.2 forge version being read as fabric 

### ISSUE THREAD

**Issue by archmichaeliii** [cam72cam/TrackAPI#6]
i am launching with only immersive engineering and immersive railroading with the track api. i get a messaging saying track api is a fabric mod. i have confirmed i have the forge version from twitch and i have attached the log when trying to launch. 
ImmersiveEngineering-0.14-96.jar
ImmersiveRailroading-1.7.3_1.14.4.jar
TrackAPI-1.2.jar
[latest.log](https://github.com/TeamOpenIndustry/TrackAPI/files/4740723/latest.log)

**Comment by cam72cam** [comment]
You must have downloaded the wrong one.  The next version will have clearer file names
